name: DripsðŸ’§ CSVs - Nightly

on:
  schedule:
    - cron: 49 23 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
        run:
            working-directory: drips/csvs

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: drips/csvs/package-lock.json

    - run: npm ci
    - run: npx tsc

    - run: node query-events.js

    - name: Git Config
      run: |
        git config user.name 'Nya Îžlimu'
        git config user.email 'info@elimu.ai'

    - name: Git Commit
      run: |
        git add *.csv
        git commit -m 'chore(dripsðŸ’§): nightly build' --allow-empty

    - name: Git Push
      run: |
        git push
