name: Node.js CI - Nightly

on:
  schedule:
    - cron: 00 03 * * *

jobs:
  nightly_build:

    runs-on: ubuntu-latest

    defaults:
        run:
            working-directory: funding-splits/distribution

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: funding-splits/distribution/package-lock.json

    - run: npm ci
    - run: npx tsc

    - run: node ./query-events.js

    - name: Git Config
      run: |
        git config user.name 'Nya Îžlimu'
        git config user.email 'info@elimu.ai'

    - name: Git Commit
      run: |
        git add *.csv
        git commit -m 'chore(distribution): nightly build'

    - name: Git Push
      run: |
        git push
